### ISSUE TITLE
﻿App crashes if you go back before the book info loads.

### ISSUE THREAD

**Issue by randomuser112358** [NHMoeDev/NHentai-android#100]
Steps to reproduce:

- Select a book.
- Try going back before the book loads.
- App crashes.

Additional info:

- NHbooks 1.8.4 from F-Droid.
- Android 6.0.1.

Traceback:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.ArrayList.clear()' on a null object reference
	at moe.feng.nhentai.ui.BookDetailsActivity.onBackPressed(BookDetailsActivity.java:645)
	at android.app.Activity.onKeyUp(Activity.java:2494)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2667)
	at android.app.Activity.dispatchKeyEvent(Activity.java:2751)
	at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:541)
	at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
	at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:319)
	at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
	at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2310)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4164)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4126)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3674)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3727)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3693)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3819)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3701)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3876)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3674)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3727)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3693)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3701)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3674)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3727)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3693)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3852)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4018)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2290)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1911)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1902)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2267)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:323)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5437)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
```

**Comment by fython** [comment]
Thanks for report.
