### ISSUE TITLE
App crashes instantly on launch, book in favorites is null - any way to retrieve favorites?

### ISSUE THREAD

**Issue by rfann** [NHMoeDev/NHentai-android#106]
I know this isn't actively maintained but I've used this app for a long time (without ever updating) and this is the first time this has occurred. I totally understand if this can't be fixed due to inactivity, but I'm hoping there's at least a way for me to retrieve my favorites. It looks like there's a database used to store book information, can I pull that file out and run queries on it (not very familiar with Android stuff)?

After favoriting something (don't remember what) I haven't been able to open the app, getting a crash error after a blank purple screen. The log is a nullpointer on bookid in favorites. If I uninstall the app, will my favorites (categories & specific releases) be lost? Is there any way to recover them when there seems to be something broken in them? Maybe they're stored in a file or something?

```Android Version: 6.0
Device Model: LG-H810
Device Manufacturer: LGE
App Version: 1.8.436

java.lang.RuntimeException: Unable to start activity ComponentInfo{moe.feng.nhentai/moe.feng.nhentai.ui.HomeActivity}: java.lang.NullPointerException: Attempt to read from field 'java.lang.String moe.feng.nhentai.model.Book.bookId' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2434)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
	at android.app.ActivityThread.access$900(ActivityThread.java:157)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5525)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String moe.feng.nhentai.model.Book.bookId' on a null object reference
	at moe.feng.nhentai.dao.FavoritesManager.reload(FavoritesManager.java:51)
	at moe.feng.nhentai.dao.FavoritesManager.getInstance(FavoritesManager.java:28)
	at moe.feng.nhentai.ui.fragment.main.HomeFragment.onCreate(HomeFragment.java:78)
	at android.app.Fragment.performCreate(Fragment.java:2207)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:942)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
	at android.app.BackStackRecord.run(BackStackRecord.java:793)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
	at android.app.FragmentController.execPendingActions(FragmentController.java:325)
	at android.app.Activity.performStart(Activity.java:6287)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2397)
	... 9 more
```

**Comment by jordyamc** [comment]
It seems that the favs are saved in a json file, on the files folder in internal memory, so the only way to get the file is using root
